import {
  BadgeCheck,
  Banknote,
  Bell,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Car,
  ChartLine,
  Check,
  CircleHelp,
  Clock3,
  Coffee,
  Construction,
  Crown,
  Dumbbell,
  Factory,
  Gem,
  Globe,
  GraduationCap,
  Handshake,
  Heart,
  Home,
  Laptop,
  Leaf,
  Lightbulb,
  Mail,
  MapPin,
  Megaphone,
  Phone,
  Plane,
  Rocket,
  Search,
  ShieldCheck,
  ShoppingCart,
  Smile,
  Sparkles,
  Star,
  Target,
  Trophy,
  Truck,
  UserCheck,
  Users,
  Wrench,
  Zap,
} from "lucide-react";
import type { FunnelOptionIcon } from "@shared/funnel";

const icons = {
  "badge-check": BadgeCheck,
  banknote: Banknote,
  bell: Bell,
  "book-open": BookOpen,
  brain: Brain,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendar: CalendarDays,
  car: Car,
  "chart-line": ChartLine,
  check: Check,
  "circle-help": CircleHelp,
  clock: Clock3,
  coffee: Coffee,
  construction: Construction,
  crown: Crown,
  dumbbell: Dumbbell,
  factory: Factory,
  gem: Gem,
  globe: Globe,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  heart: Heart,
  home: Home,
  laptop: Laptop,
  leaf: Leaf,
  lightbulb: Lightbulb,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  phone: Phone,
  plane: Plane,
  rocket: Rocket,
  search: Search,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  trophy: Trophy,
  truck: Truck,
  "user-check": UserCheck,
  users: Users,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<FunnelOptionIcon, typeof Check>;

export function FunnelIcon({ name, className }: { name: FunnelOptionIcon | string; className?: string }) {
  const Icon = icons[name as FunnelOptionIcon] ?? Sparkles;
  return <Icon className={className} aria-hidden="true" strokeWidth={1.8} />;
}
