import type { FunnelConfig } from "./funnel";

export const DEFAULT_FUNNEL_ID = "10000000-0000-4000-8000-000000000001";

export const defaultFunnel: FunnelConfig = {
  schemaVersion: 1,
  id: DEFAULT_FUNNEL_ID,
  slug: "karriere",
  title: "Deine Karriere bei uns",
  status: "published",
  isPublished: true,
  notificationEmail: "",
  allowedEmbedOrigins: [],
  brand: {
    logoUrl: "",
    logoAlt: "Unternehmenslogo",
    faviconUrl: "",
    accentColor: "#0165c3",
    backgroundColor: "#f4f8fc",
    surfaceColor: "#ffffff",
    textColor: "#10253f",
    choiceBackgroundColor: "#ffffff",
    choiceTextColor: "#10253f",
    choiceSelectedBackgroundColor: "#eef7ff",
    choiceSelectedTextColor: "#10253f",
    choiceSelectedBorderColor: "#0165c3",
  },
  socialProof: {
    enabled: true,
    eyebrow: "Einfach & vertraulich",
    text: "In rund 2 Minuten bewerben – ohne Anschreiben.",
  },
  privacyUrl: "https://example.org/datenschutz",
  privacyLabel: "Datenschutzerklärung",
  legal: {
    imprintTitle: "Impressum",
    imprintContent: "Die vollständigen Anbieterangaben für diesen Funnel werden derzeit ergänzt.",
  },
  postSubmit: {
    mode: "message",
    redirectUrl: "",
  },
  metaTracking: {
    enabled: false,
    pixelId: "",
    eventName: "Lead",
    conversionTrigger: "submit",
  },
  pages: [
    {
      id: "page-start",
      type: "start",
      name: "Startseite",
      eyebrow: "Dein nächster Karriereschritt",
      title: "Finde heraus, ob wir zueinander passen.",
      description:
        "Beantworte wenige kurze Fragen und lerne uns unverbindlich kennen. Deine Angaben behandeln wir selbstverständlich vertraulich.",
      buttonLabel: "Jetzt starten",
      heroImageUrl: "",
      bullets: ["Kein Anschreiben nötig", "Mobil in wenigen Minuten", "Schnelle persönliche Rückmeldung"],
      trustNote: "Kostenlos · Unverbindlich · Datenschutzkonform",
    },
    {
      id: "page-role",
      type: "choice-grid",
      name: "Arbeitsbereich",
      eyebrow: "Kurze Frage",
      title: "Welcher Bereich passt am besten zu dir?",
      description: "Wähle die Antwort aus, die deiner Wunschposition am nächsten kommt.",
      buttonLabel: "Weiter",
      questionKey: "arbeitsbereich",
      allowMultiple: false,
      options: [
        { id: "role-sales", label: "Vertrieb", value: "vertrieb", icon: "target" },
        { id: "role-office", label: "Office", value: "office", icon: "building" },
        { id: "role-tech", label: "Technik", value: "technik", icon: "rocket" },
        { id: "role-other", label: "Andere Rolle", value: "andere", icon: "sparkles" },
      ],
    },
    {
      id: "page-experience",
      type: "choice-list",
      name: "Berufserfahrung",
      eyebrow: "Kurze Frage",
      title: "Wie viel Berufserfahrung bringst du mit?",
      description: "Eine ehrliche Einschätzung genügt – es gibt keine falsche Antwort.",
      buttonLabel: "Weiter",
      questionKey: "berufserfahrung",
      allowMultiple: false,
      options: [
        { id: "exp-entry", label: "Ich starte gerade erst", value: "einstieg", icon: "graduation-cap" },
        { id: "exp-junior", label: "1–3 Jahre", value: "1-3", icon: "calendar" },
        { id: "exp-senior", label: "Mehr als 3 Jahre", value: "3-plus", icon: "star" },
        { id: "exp-change", label: "Ich bin Quereinsteiger:in", value: "quereinstieg", icon: "sparkles" },
      ],
    },
    {
      id: "page-contact",
      type: "contact",
      name: "Kontaktdaten",
      eyebrow: "Fast geschafft",
      title: "Fast geschafft – wie erreichen wir dich?",
      description: "Hinterlasse deine Kontaktdaten. Wir melden uns persönlich und vertraulich bei dir.",
      buttonLabel: "Bewerbung absenden",
      fields: [
        { key: "name", label: "Vor- und Nachname", placeholder: "Max Mustermann", enabled: true, required: true, inputType: "text" },
        { key: "company", label: "Aktuelles Unternehmen", placeholder: "Optional", enabled: true, required: false, inputType: "text" },
        { key: "email", label: "E-Mail-Adresse", placeholder: "max@beispiel.de", enabled: true, required: true, inputType: "email" },
        { key: "phone", label: "Telefonnummer", placeholder: "+49 ...", enabled: true, required: true, inputType: "tel" },
        { key: "message", label: "Was möchtest du uns noch sagen?", placeholder: "Optionaler Hinweis", enabled: true, required: false, inputType: "textarea" },
      ],
      consentLabel:
        "Ich stimme der Verarbeitung meiner Angaben zum Zweck der Kontaktaufnahme und des Bewerbungsverfahrens zu.",
      consentRequired: true,
      resumeEnabled: true,
      resumeRequired: false,
      resumeLabel: "Lebenslauf hochladen (optional)",
      successTitle: "Vielen Dank für deine Bewerbung!",
      successText: "Deine Angaben sind sicher eingegangen. Wir melden uns zeitnah persönlich bei dir.",
    },
  ],
};
